sudo: required
services:
 - docker

before_install:
 - docker build -t abhinavgupta96/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true abhinavgupta96/react-test npm test -- --coverage

after_success:
 - docker build -t abhinavgupta96/multi-client ./client
 - docker build -t abhinavgupta96/multi-nginx ./nginx
 - docker build -t abhinavgupta96/multi-server ./server
 - docker build -t abhinavgupta96/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push abhinavgupta96/multi-client
 - docker push abhinavgupta96/multi-nginx
 - docker push abhinavgupta96/multi-server
 - docker push abhinavgupta96/multi-worker

